[[repos]]
repo = "https://github.com/qoomon/git-conventional-commits"
rev = "v2.9.0"
hooks = [{ id = "conventional-commits" }]

[[repos]]
repo = "https://github.com/streetsidesoftware/cspell-cli"
rev = "v10.0.0"
hooks = [
  { id = "cspell" },
  { id = "cspell", name = "cspell", args = [
    "--no-must-find-files",
    "--no-progress",
    "--no-summary",
    "--files",
    "git/COMMIT_EDITMSG",
  ], stages = [
    "commit-msg",
  ], always_run = true },
]

[[repos]]
repo = "https://github.com/RobertCraigie/pyright-python"
rev = "v1.1.409"
hooks = [{ id = "pyright" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12"
hooks = [
	{ id = "ruff-check" },
	{ id = "ruff-format", "types_or" = [
		"python",
		"pyi",
		"markdown",
	] },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "prettier"
name = "prettier"
entry = "pnpm dlx pretty-quick --no-restage --staged"
language = "system"
files = "\\.(css|scss|htm|html|js|jsx|ts|tsx|json|yml|yaml|md)$"
