[[repos]]
repo = "https://github.com/qoomon/git-conventional-commits"
rev = "v2.9.0"
hooks = [{ id = "conventional-commits" }]

[[repos]]
repo = "https://github.com/streetsidesoftware/cspell-cli"
rev = "v10.0.0"
hooks = [
  { id = "cspell" },
  { id = "cspell", name = "cspell", args = [
    "--no-must-find-files",
    "--no-progress",
    "--no-summary",
    "--files",
    "git/COMMIT_EDITMSG",
  ], stages = [
    "commit-msg",
  ], always_run = true },
]

[[repos]]
repo = "https://github.com/RobertCraigie/pyright-python"
rev = "v1.1.409"
hooks = [{ id = "pyright" }]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12"
hooks = [{ id = "ruff-check" }, { id = "ruff-format" }]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "taplo-format"
name = "taplo format"
entry = "uvx taplo fmt"
language = "system"
types = ["toml"]
pass_filenames = true
require_serial = true

[[repos.hooks]]
id = "taplo-check"
name = "taplo check"
entry = "uvx taplo check"
language = "system"
types = ["toml"]
pass_filenames = true
require_serial = true

[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.19.0"
hooks = [{ id = "yamlfmt" }]
